---
# yaml-language-server: $schema=https://raw.githubusercontent.com/suzuki-shunsuke/pinact/refs/heads/main/json-schema/pinact.json
version: 3

ignore_actions:
  - name: marvinpinto/action-automatic-releases
    ref: latest
