#!/bin/sh
#
# Insert selected git-bug issue identifier in the comment.
# if no selected issue, print in comments the list of open issues.
#
cmtChar=`git config --get core.commentchar`
hashChar="#"
if [ "$cmtChar" = "" ]
then
	cmtChar="#"
fi
if [ "$cmtChar" = "#" ]
then
	hashChar=":"
fi

case "$2,$3" in
#  merge,)
#    /usr/bin/perl -i.bak -ne 's/^/# /, s/^# #/#/ if /^Conflicts/ .. /#/; print' "$1" ;;
#
# ,|template,)
#   /usr/bin/perl -i.bak -pe '
#      print "\n" . `git diff --cached --name-status -r`
#	 if /^#/ && $first++ == ' "$1" ;;

  *) 
        ISSUE=`git bug show --id`
	if [ "$ISSUE" = "" ]
	then
		echo "$cmtChar !!!!! insert $hashChar<issue_id> in your comment, pick one in list below." >> "$1"
		git bug ls status:open |sed 's/ open\t/ /'| sed "s/^/$cmtChar/" >> "$1"
	else
		sed -i "1i$hashChar$ISSUE " "$1"
	fi
	;;
esac
