---
name: lint

on:
  workflow_call:

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check spelling
        uses: codespell-project/actions-codespell@v2
